DreamworldSolutions/dw-select

dw-select-dialog.js, package.json
=> Issue: Apply button is enabled if multi-select dropdown has initially

dw-select-dialog.js
=> fix: Increase bottom padding below the last row dialog when there is no

dw-select-css.js, dw-select.js
card link: https://a.kerika.net/C7r/board/N2O6/Y5I6
=> feat: add appendTo property support.

dw-select-dialog.js
card link: https://a.kerika.net/C7r/board/N2O6/Y6TF?tab=description
=> fix: user selection made is erased when items are changed.

dw-select-trigger.js, dw-select.js
https://a.kerika.net/ZHvl/board/ZKIj/Zqfk
=> feat: START add trail icon in dw-select-trigger

dw-select-group-item.js
https://a.kerika.net/ZHvl/board/ZKIj/Zqi3
=> feat: START update typography

demo/select-demo.js, dw-select-dialog.js, dw-select.js
https://a.kerika.net/ZHvl/board/ZKIj/Zqiy
=> feat: START add property in dw-select

dw-select-trigger.js
- introduce --dw-icon-color for trailing icon
=> feat: trigger element trailing icon color

README.md, demo/select-demo.js, demo/utils.js, dw-select-base-dialog.js, dw-select-core-dialog.js, dw-select-trigger.js, dw-select.js, utils.js
- change dialog name to `dw-select-core-dialog`
- introduce `checkvality()` and `reportValidity()` to select
=> feat: introduce new property `queryFilter`

demo/select-demo.js, dw-select-base-dialog.js, dw-select.js
- remove custom getter/setter
- use willUpdate for observer on property change
=> feat: START expand group when search start and dialog is popover

dw-select-base-dialog.js
- first item should be activated
=> feat: when no selected value - on dialog open

demo/select-demo.js, dw-select.js, utils.js
- When a query includes multiple words, it should match only records where all words are matched somewhere.
=> feat: query filter refactor

demo/index.html, demo/select-demo.js, demo/utils.js, dw-select-base-dialog.js, dw-select.js, utils.js, web-dev-server.config.mjs
- Set dialog max-width according to trigger element position on the viewport
- when the dialog opens scroll to the selected item
=> feat: START trigger element should be visible when dialog open

demo/select-demo.js, dw-select.js
- highlight bg color
- selected item bg color
=> feat: set default custom css property

dw-select-group-item.js
- collapsible false - group item typography subtitle2
=> feat: group item style update

dw-select.js
it does't work when user selects an item from the drop-down using mouse
=> fix: clear selection on blur

demo/select-demo.js, dw-select-base-dialog.js, dw-select.js
- label not update when query not available and selection is done.
=> feat: make diffrence  between activated and selected item

dw-select-trigger.js, dw-select.js
=> feat(dw-select): on selection focus back to input field

dw-select-base-dialog.js, dw-select.js
Typed character is auto-erased. So, feature doesn't work at all
=> fix: allowNewValue behaviour

README.md, dw-select-base-dialog.js, dw-select.js
=> feat: loading view enhancement

dw-select-base-dialog.js, package.json, yarn.lock
- update dialog, tippy shown instance after 250 ms
=> feat: list item overlape

dw-select-base-dialog.js, dw-select.js
behaivours for this feature has been fixed in context of desktop usage, and very basic use required for SMPV (admin-ui).
Detailed testing & bug-fixes will be done later.
=> fix: allowNewValue -> allowNewItem

README.md, dw-select-base-dialog.js, dw-select.js, package.json, yarn.lock
card link: https://a.kerika.net/acc_7araR1FVpSBR4YqEpigNdw/board/brd_5tqvSAclSPxioQ0liA8gr8/crd_50zda82HjXrLUZ2br7OMku
=> feat: provide a way to prepend items.

dw-select.js
- separate template for trigger and dialog
=> fix(select): validation required refactor

utils.js
card link: https://a.kerika.net/acc_7araR1FVpSBR4YqEpigNdw/board/brd_7URTPkJW8a9n1NEkgCYTxk/crd_5M45e9JAX0wceVNGX2fZJ0
=> fix: type error e.trim is not a function

dw-multi-select-base-dialog.js, dw-multi-select.js, dw-select-base-dialog.js, dw-select.js, sort-items.js
card link: https://a.kerika.net/acc_7araR1FVpSBR4YqEpigNdw/board/brd_4jC4aIuKkmq39kuXeWciIe/crd_2vIfgAR3A17xGA5xMov7iD?tab=description
=> fix: improve account autocomplete to show results by relevance.
